/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as tabsBlogsRouteImport } from './routes/(tabs)/blogs'
import { Route as tabsAboutRouteImport } from './routes/(tabs)/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsBlogsRoute = tabsBlogsRouteImport.update({
  id: '/(tabs)/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsAboutRoute = tabsAboutRouteImport.update({
  id: '/(tabs)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof tabsAboutRoute
  '/blogs': typeof tabsBlogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof tabsAboutRoute
  '/blogs': typeof tabsBlogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tabs)/about': typeof tabsAboutRoute
  '/(tabs)/blogs': typeof tabsBlogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blogs'
  id: '__root__' | '/' | '/(tabs)/about' | '/(tabs)/blogs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  tabsAboutRoute: typeof tabsAboutRoute
  tabsBlogsRoute: typeof tabsBlogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/blogs': {
      id: '/(tabs)/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof tabsBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/about': {
      id: '/(tabs)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof tabsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  tabsAboutRoute: tabsAboutRoute,
  tabsBlogsRoute: tabsBlogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
